"""
Geometry.py: A collection of functions to aid in the movement of our entities.
"""

def is_in_polygon(vertices, point):
    """
    Given a list of vertices and a point, returns whether or not the point is within the polygon generated by the vertices. Currently uses a bounding box approach and does not accept Vector2 vertices.
    """
    x_min = vertices[0][0]
    x_max = vertices[0][0]
    y_min = vertices[0][1]
    y_max = vertices[0][1]
    # sides = []

    # get max and mins
    for _ in vertices:
        if x_min > _[0]:
            x_min = _[0]

        if x_max < _[0]:
            x_max = _[0]

        if y_min > _[1]:
            y_min = _[1]
        
        if y_max < _[1]:
            y_max = _[1]

    # padding for our bounding box
    padding = ((x_max - x_min) / 100) * 3 # 3 %

    is_not_inside = point[0] < (x_min-padding) 
    is_not_inside = is_not_inside or point[0] > (x_max+padding)
    is_not_inside = is_not_inside or point[1] < (y_min-padding)
    is_not_inside = is_not_inside or point[1] > (y_max+padding)

    return is_not_inside == False
    # potentially more refined implementation
    # ray_start = (x_min - e, point[1])
    # ray_end = point

    # for i in xrange(0, len(vertices) - 1):
    #     sides.append((vertices[i], vertices[i+1]))

    # #find intersections
